language: python
install: pip install -e .
script: py.test

python:
    - "pypy"
    - "pypy3"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.8-dev"
      dist: xenial
      sudo: true
